from .user_recommend_models.random_model import RandomUserRecommendationsModel
from .team_recommend_models.random_model import RandomTeamRecommendationsModel
from .hack_recommend_models.random_model import RandomHackRecommendationsModel
from .base_model import AbstractRecommendsModel